<?php

namespace AppBundle\Repository;

/**
 * RarCustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RarCustomerRepository extends \Doctrine\ORM\EntityRepository
{
}
