<?php

namespace AppBundle\Repository;

/**
 * RarConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RarConfigurationRepository extends \Doctrine\ORM\EntityRepository
{
}
