<?php

namespace AppBundle\Repository;

/**
 * RarLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RarLocationRepository extends \Doctrine\ORM\EntityRepository
{
}
