<?php

namespace AppBundle\Repository;

/**
 * RarMeetingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RarMeetingRepository extends \Doctrine\ORM\EntityRepository
{
}
