<?php

namespace AppBundle\Repository;

/**
 * RarMatterProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RarMatterProviderRepository extends \Doctrine\ORM\EntityRepository
{
}
