<?php

namespace AppBundle\Repository;

/**
 * RarMatterAttributedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RarMatterAttributedRepository extends \Doctrine\ORM\EntityRepository
{
}
