<?php

namespace AppBundle\Repository;

/**
 * RarMatterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RarMatterRepository extends \Doctrine\ORM\EntityRepository
{
}
