<?php

namespace AppBundle\Repository;

/**
 * RarModelOrderedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RarModelOrderedRepository extends \Doctrine\ORM\EntityRepository
{
}
