<?php

namespace AppBundle\Repository;

/**
 * RarModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RarModelRepository extends \Doctrine\ORM\EntityRepository
{
}
