<?php

namespace AppBundle\Repository;

/**
 * RarNotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RarNotesRepository extends \Doctrine\ORM\EntityRepository
{
}
