<?php

namespace AppBundle\Repository;

/**
 * RarOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RarOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
