<?php

namespace AppBundle\Repository;

/**
 * RarOrderNotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RarOrderNotesRepository extends \Doctrine\ORM\EntityRepository
{
}
