<?php

namespace AppBundle\Repository;

/**
 * RarProdBasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RarProdBasketRepository extends \Doctrine\ORM\EntityRepository
{
}
