<?php

namespace AppBundle\Repository;

/**
 * RarProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RarProviderRepository extends \Doctrine\ORM\EntityRepository
{
}
