<?php

namespace AppBundle\Repository;

/**
 * RarPublicFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RarPublicFormRepository extends \Doctrine\ORM\EntityRepository
{
}
