<?php

namespace AppBundle\Repository;

/**
 * RarPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RarPaymentRepository extends \Doctrine\ORM\EntityRepository
{
}
