<?php

namespace AppBundle\Repository;

/**
 * RarPriceMatterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RarPriceMatterRepository extends \Doctrine\ORM\EntityRepository
{
}
