<?php

namespace AppBundle\Repository;

/**
 * RarShopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RarShopRepository extends \Doctrine\ORM\EntityRepository
{
}
