<?php

namespace AppBundle\Repository;

/**
 * StockLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RarStockLogRepository extends \Doctrine\ORM\EntityRepository
{
}
