<?php

namespace AppBundle\Repository;

/**
 * RarUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RarUserRepository extends \Doctrine\ORM\EntityRepository
{
}
