<?php

namespace AppBundle\Repository;

/**
 * RarWorkroomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RarWorkroomRepository extends \Doctrine\ORM\EntityRepository
{
}
